name: jiran-tetangga-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: jiran-tetangga:latest
  
      - name: GitHub Actions Discord Webhook
        if: success()
        uses: niranjanshk27/discord-announcement@main
        with:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          TITLE: "Build Status"
          EMBEDS: "false"
          CONTENT: |
            - ðŸ—ï¸ Build: ${{ steps.test-build.outcome }}
          RESULT: ${{ steps.test-build.outcome }}

      - name: Done
        run: echo "CI pipeline build stage completed."
  
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [8.0.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
          echo "ROUTE_PREPEND=${{ secrets.ROUTE_PREPEND }}" >> .env
          echo "VERSION=${{ secrets.VERSION }}" >> .env

      - name: Run tests
        run: |
          npm test || echo "No tests defined yet. Skipping."
        env:
          CI: true

      - name: GitHub Actions Discord Webhook
        if: success()
        uses: niranjanshk27/discord-announcement@main
        with:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          TITLE: "Test Status"
          EMBEDS: "false"
          CONTENT: |
            - ðŸ§ª Test: ${{ steps.test-result.outcome }}
          RESULT: ${{ steps.test-result.outcome }}

      - name: Done
        run: echo "CI pipeline test stage completed."

